import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  container:{
    backgroundColor:'white',
    flex:1,
  },
  list:{
    flex:1
  },
  section:{
    paddingLeft:24,
    height:35,
    flex:1,
    flexDirection:'row',
    alignItems:'center',
    backgroundColor:'#eee',
  },
  sectionTitle:{
    fontWeight:'bold',
  },
  avatar:{
    width:44,height:44,
    borderRadius:23,
    overflow:'hidden',
    backgroundColor:'transparent',
    display:'flex',
    alignItems:'center',
    justifyContent:'center',
    marginRight:18,
    marginLeft:18,
    borderWidth:1,
    borderColor:'#eee'
  },
  contactTouch:{
    flex:1,
    flexDirection:'row',
    justifyContent:'center',
    height:80,
    alignItems:'center'
  },
  contactContent:{
    flex:1,
  },
  contactName:{
    marginRight:12,
    fontSize:16,
    fontWeight:'bold',
    color:'#666',
  },
  backSwipeRow:{
    backgroundColor:'#DB5554',
    flex:1,
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'flex-end'
  },
  frontSwipeRow:{
    backgroundColor:'white',
    flex:1,
    height:80
  }
})