import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  header:{
    width:'100%',
    backgroundColor:'#eee',
    borderTopColor:'#ddd',
    borderTopWidth:1,
    borderBottomColor:'#ddd',
    borderBottomWidth:1,
    paddingLeft:25,
    height:35,
    display:'flex',
    flexDirection:'row',
    alignItems:'center',
  },
  headerTitle:{
    fontSize:10,
    color:'grey',
    textTransform:'uppercase',
  },
  body:{
    width:'100%',
    paddingLeft:20,
    display:'flex',
    flexDirection:'column',
    alignItems:'flex-start',
    paddingTop:15,
    paddingBottom:15,
  },
  optionWrap:{
    display:'flex',
    flexDirection:'row',
    alignItems:'center',
    height:50
  },
  optionLabel:{
    fontSize:15,
    marginRight:10,
    marginLeft:4,
    color:'#666'
  },
  optionSuffix:{
    fontSize:15,
    color:'#aaa',
    marginLeft:10,
  },
  numberInput:{
    borderWidth:1,
    borderColor:'#bbb',
    height:35,
    paddingLeft:6,
    paddingRight:6,
    borderRadius:5,
    width:75,
    textAlign:'center',
    fontSize:15,
    paddingBottom:7
  },
  dateInput:{
    borderWidth:1,
    borderColor:'#bbb',
    height:35,
    paddingLeft:6,
    paddingRight:6,
    borderRadius:5,
    width:150,
    fontSize:15,
    display:'flex',
    flexDirection:'row',
    alignItems:'center'
  },
  dateValue:{
    marginLeft:8
  }
})