import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  wrap:{
    flex:1,
    position:'absolute',
    top:25,left:0,bottom:0,right:0,
    flexDirection:'column',
    justifyContent:'center',
    alignItems:'center',
    backgroundColor:'black'
  },
  buttonsWrap:{
    marginTop:40,
    display:'flex',
    flexDirection:'row',
    width:'100%',
    justifyContent:'space-around'
  },
  button:{
    height:46,
    borderRadius:23,
    width:120,
    display:'flex',
    justifyContent:'center',
    alignItems:'center'
  },
  full:{
    flex:1,position:'absolute',
    top:0,left:0,right:0,bottom:0,
  },
  toolbar:{
    position:'absolute',
    bottom:25,
    backgroundColor:'transparent',
    display:'flex',
    flexDirection:'row',
    justifyContent:'space-around',
    alignItems:'center',
    zIndex:25,
  },
  round:{
    width:50,height:50,
    backgroundColor:'#ddd',
    borderRadius:25,
    display:'flex',
    justifyContent:'center',
    alignItems:'center'
  },
  bigVid:{
    position:'absolute',
    top:0,left:0,bottom:0,right:0,
    zIndex:9,
    overflow:'hidden'
  },
  smallVid:{
    height:150,
    width:150,
    borderColor:'white',
    borderWidth:1,
    position:'absolute',
    top:20,left:20,
    zIndex:999,
    overflow:'hidden'
  }
})