import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  wrap:{
    flex:1,
    justifyContent:'center',
    alignItems:'center',
  },
  scroller:{
    flexGrow:1,
    width:'100%',
    overflow:'scroll',
    flexDirection:'column',
    borderTopColor:'#E9EAEC',
    borderTopWidth:1,
  },
  payment:{
    width:'100%',
    height:55,
    maxHeight:55,minHeight:55,
    display:'flex',
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'space-between',
    borderBottomColor:'#E9EAEC',
    borderBottomWidth:1,
  },
  mid:{
    flex:1,
    display:'flex',
    flexDirection:'row',
    alignItems:'center',
  },
  loading:{
    flexGrow:1,
    width:'100%',
    justifyContent:'center',
    marginTop:40
  },
  amountWrap:{
    marginRight:10,
    marginLeft:40,
    display:'flex',
    alignItems:'center',
    justifyContent:'center',
    flexDirection:'row',
  },
  amount:{
    marginRight:10,
    fontSize:14,
    fontWeight:'bold'
  },
  sat:{
    marginRight:10,
    color:'#aaa',
    fontSize:12,
  },
  contact:{
    fontSize:12,
    marginLeft:10
  }
})