import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  inviteQR: {
    width: 40, height: 40,
    overflow: 'hidden',
    backgroundColor: 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    marginRight: 18,
    marginLeft: 18,
  },
  avatarWrap: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    width: 52, height: 52,
    marginRight: 18,
    marginLeft: 10,
  },
  avatar: {
    width: 52, height: 52,
    borderRadius: 26,
    backgroundColor: 'transparent',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    borderWidth: 1,
    borderColor: '#eee',
    position: 'relative',
    overflow: 'hidden',
  },
  chatRow: {
    height: 80,
    width: '100%',
    display: 'flex',
    alignItems: 'center',
    flexDirection: 'row',
    borderBottomWidth: 1,
    borderBottomColor: '#e5e5e5',
    backgroundColor: 'white',
  },
  chatContent: {
    display: 'flex',
    flexDirection: 'column',
    flex: 1,
  },
  chatContentTop: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
    flex: 1,
    maxHeight: 28
  },
  invitePrice: {
    height: 22,
    color: 'white',
    backgroundColor: '#64c684',
    paddingLeft: 10,
    paddingRight: 10,
    paddingTop: 3,
    paddingBottom: 3,
    borderRadius: 3,
    fontSize: 12,
    marginRight: 20,
  },
  chatName: {
    marginRight: 12,
    fontSize: 16,
    fontWeight: 'bold',
    color: '#666',
    marginBottom: 4,
  },
  chatMsgWrap: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
  },
  chatMsg: {
    color: '#7e7e7e',
    fontSize: 13,
  },
})