import { StyleSheet } from 'react-native'

export default StyleSheet.create({
  wrapper:{
    flex:1,
    alignItems: 'center',
    justifyContent: 'flex-end',
  },
  modal:{
    margin:0,
    maxHeight:200,
    height:200,
    position:'absolute',
    width:'100%',
    justifyContent: 'flex-end',
  },
  main:{
    backgroundColor:'white',
    borderTopLeftRadius:20,
    borderTopRightRadius:20,
    marginTop:5,
    flex:1,
    width:'100%'
  },
  header:{
    height:50,
    minHeight:50,
    width:'100%',
    paddingLeft:0,
    marginLeft:10,
    marginTop:10,
    display:'flex',
    flexDirection:'row',
    justifyContent:'space-between',
    alignItems:'center'
  },
  headerLabel:{
    fontWeight:'bold',
    fontSize:16,
    color:'#6289FD',
    marginRight:8,
  },
  headerAmt:{
    fontWeight:'bold',
    fontSize:20,
    marginRight:8,
  },
  headerSat:{
    fontSize:12,
    color:'#aaa'
  },
  headerLefty:{
    backgroundColor:'white',
    display:'flex',
    flexDirection:'row',
    alignItems:'center',
    marginLeft:20
  },
  confirmWrap:{
    width:'100%',
    display:'flex',
    alignItems:'center',
    height:100,
    marginTop:25,
    marginBottom:20
  },
  confirm:{
    backgroundColor:'#6289FD',
    height:35,
    width:150,
    display:'flex',
    flexDirection:'row',
    alignItems:'center',
    justifyContent:'center',
    borderRadius:20,
  },
})
